apiVersion: v1
kind: Secret
metadata:
  name: lecex
  namespace: lecexnamespace
data:
  admin-password: YWRtaW4xMjM=
  app-key: NjFhMTBiNjVjMWY5Mjg5MTYxMzhhYzMzOTMxZGI2NTc=
  mysql-user-password: YWRtaW4xMjM=
  mysql-pay-password: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lecex
  namespace: lecexnamespace
---