apiVersion: v1
kind: Secret
metadata:
  name: lecex
  namespace: lecex
data:
  admin-password: YWRtaW4xMjM=
  app-key: NjFhMTBiNjVjMWY5Mjg5MTYxMzhhYzMzOTMxZGI2NTc=
  mysql-user-password: YWRtaW4xMjM=
  mysql-pay-password: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lecex
  namespace: lecex
data:
  registry: "nats"
  registry-address: "nats-client"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lecex-user
  namespace: lecex
data:
  db-host: 172.16.2.9
  db-user: "lecex_user"
  db-name: "lecex_user"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lecex-pay
  namespace: lecex
data:
  db-host: 172.16.2.9
  db-user: "lecex_pay"
  db-name: "lecex_pay"
---