# 负载均衡
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: micro-rpc
  namespace: lecex
spec:
  rules:
  - host: xip.io
    http:
      paths:
        - backend:
            serviceName: micro-rpc
            servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: micro-rpc
  namespace: lecex
spec:
  selector:
    app: micro-rpc
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-rpc
  namespace: lecex
  labels:
    app: micro-rpc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: micro-rpc
  template:
    metadata:
      labels:
        app: micro-rpc
    spec:
      containers:
        - name: micro-rpc
          image: registry.cn-hangzhou.aliyuncs.com/lecex/micro
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "api"
            - "--handler=rpc"
            - "--enable_cors=true"
          env:
          - name: MICRO_API_NAMESPACE
            value: go.micro.api
          - name: MICRO_SERVER_NAME
            value: micro-rpc
          - name: MICRO_SERVER_ADDRESS
            value: 0.0.0.0:8989
          - name: MICRO_ENABLE_STATS
            value: "true"
          - name: MICRO_REGISTRY
            value: "nats"
          - name: MICRO_REGISTRY_ADDRESS
            value: "{{ include "lecex.fullname" . }}-nats-client"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        - name: health
          command: [
            "/health",
            "--health_address=0.0.0.0:8081",
            "--server_name=micro-rpc",
            "--server_address=0.0.0.0:8989"
          ]
          image: microhq/health:kubernetes
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3


