dependencies:
- name: redis
  version: 10.x.x
  repository: http://mirror.azure.cn/kubernetes/charts/
- name: mariadb
  version: 7.x.x
  repository: http://mirror.azure.cn/kubernetes/charts/
  alias: mariadb
- name: mysqldump
  version: 2.x.x
  repository: http://mirror.azure.cn/kubernetes/charts/
  alias: mysqldump